// eslint-disable-next-line
const types = {
  TEACHER_LOGIN_API: "TEACHER_LOGIN_API",
  SET_TEACHER_LOGIN: "SET_TEACHER_LOGIN",
  SET_TEACHER_LOGIN_ERROR: "SET_TEACHER_LOGIN_ERROR",

  TEACHER_SIGN_UP_API: "TEACHER_SIGN_UP_API",
  SET_TEACHER_SIGN_UP: "SET_TEACHER_SIGN_UP",
  SET_TEACHER_SIGN_UP_ERROR: "SET_TEACHER_SIGN_UP_ERROR",

  STUDENT_LOGIN_API: "STUDENT_LOGIN_API",
  SET_STUDENT_LOGIN: "SET_STUDENT_LOGIN",
  SET_STUDENT_LOGIN_ERROR: "SET_STUDENT_LOGIN_ERROR",

  SET_LOGOUT: "SET_LOGOUT",
  SET_SIGNUP_STATE: "SET_SIGNUP_STATE",

  TEACHER_STATUS_API: "TEACHER_STATUS_API",
  SET_TEACHER_STATUS: "SET_TEACHER_STATUS",
  SET_TEACHER_STATUS_ERROR: "SET_TEACHER_STATUS_ERROR",

  USERS_PROFILE_API: "USERS_PROFILE_API",
  SET_USERS_PROFILE_STATUS: "SET_USERS_PROFILE",
  SET_USERS_PROFILE_STATUS_ERROR: "SET_USERS_PROFILE_ERROR",

  USERS_ENTITIES_API: "USERS_ENTITIES_API",
  SET_USERS_ENTITIES_STATUS: "SET_USERS_ENTITIES",
  SET_USERS_ENTITIES_STATUS_ERROR: "SET_USERS_ENTITIES_ERROR",
};

export default types;
