// eslint-disable-next-line
const types = {
  USERS_LOGIN_API: "USERS_LOGIN_API",
  SET_USERS_LOGIN: "SET_USERS_LOGIN",
  SET_USERS_LOGIN_ERROR: "SET_USERS_LOGIN_ERROR",

  USERS_SIGN_UP_API: "USERS_SIGN_UP_API",
  SET_USERS_SIGN_UP: "SET_USERS_SIGN_UP",
  SET_USERS_SIGN_UP_ERROR: "SET_USERS_SIGN_UP_ERROR",

  SET_LOGOUT: "SET_LOGOUT",
  SET_SIGNUP_STATE: "SET_SIGNUP_STATE",

  USERS_STATUS_API: "USERS_STATUS_API",
  SET_USERS_STATUS: "SET_USERS_STATUS",
  SET_USERS_STATUS_ERROR: "SET_USERS_STATUS_ERROR",

  USERS_PROFILE_API: "USERS_PROFILE_API",
  SET_USERS_PROFILE_STATUS: "SET_USERS_PROFILE",
  SET_USERS_PROFILE_STATUS_ERROR: "SET_USERS_PROFILE_ERROR",

  USERS_ENTITIES_API: "USERS_ENTITIES_API",
  SET_USERS_ENTITIES_STATUS: "SET_USERS_ENTITIES",
  SET_USERS_ENTITIES_STATUS_ERROR: "SET_USERS_ENTITIES_ERROR",
};

export default types;
