// eslint-disable-next-line
const types = {
  TEACHER_LOGIN_API: "TEACHER_LOGIN_API",
  SET_TEACHER_LOGIN: "SET_TEACHER_LOGIN",
  SET_TEACHER_LOGIN_ERROR: "SET_TEACHER_LOGIN_ERROR",

  TEACHER_SIGN_UP_API: "TEACHER_SIGN_UP_API",
  SET_TEACHER_SIGN_UP: "SET_TEACHER_SIGN_UP",
  SET_TEACHER_SIGN_UP_ERROR: "SET_TEACHER_SIGN_UP_ERROR",

  STUDENT_LOGIN_API: "STUDENT_LOGIN_API",
  SET_STUDENT_LOGIN: "SET_STUDENT_LOGIN",
  SET_STUDENT_LOGIN_ERROR: "SET_STUDENT_LOGIN_ERROR",

  SET_LOGOUT: "SET_LOGOUT",
  SET_SIGNUP_STATE: "SET_SIGNUP_STATE",

  TEACHER_ADDRESS_API: "TEACHER_ADDRESS_API",
  SET_TEACHER_ADDRESS: "SET_TEACHER_ADDRESS",
  SET_TEACHER_ADDRESS_ERROR: "SET_TEACHER_ADDRESS_ERROR",

  TEACHER_CLASSES_API: "TEACHER_CLASSES_API",
  SET_TEACHER_CLASSES: "SET_TEACHER_CLASSES",
  SET_TEACHER_CLASSES_ERROR: "SET_TEACHER_CLASSES_ERROR",

  TEACHER_SUBJECTS_API: "TEACHER_SUBJECTS_API",
  SET_TEACHER_SUBJECTS: "SET_TEACHER_SUBJECTS",
  SET_TEACHER_SUBJECTS_ERROR: "SET_TEACHER_SUBJECTS_ERROR",

  TEACHER_TIMES_API: "TEACHER_TIMES_API",
  SET_TEACHER_TIMES: "SET_TEACHER_TIMES",
  SET_TEACHER_TIMES_ERROR: "SET_TEACHER_TIMES_ERROR",
};

export default types;
